### ISSUE TITLE
Deploy to Hockey is not working using fastlane 2.86.2

### ISSUE THREAD

**Issue by maskedpear** [theappbusiness/MasterFastfile#52]
Since updating fastlane to current latest (2.86.2) we are not able to deploy builds to Hockey. 

After some research, I found out that `get_version_number` action has changed.
https://github.com/fastlane/fastlane/blob/5846fe56a548f056c5f875c05fa4b900d0d35558/fastlane/lib/fastlane/actions/get_version_number.rb

That caused a lot of issues to many devs. Please check here https://github.com/fastlane/fastlane/issues/12119.

Apparently the if you call get_version_number without any parameters will prompt you to enter the target if running manually. However, as we do run Jenkins tasks, tasks are failing
`[!] Could not retrieve response as fastlane runs in non-interactive mode`

I just wanted to make you aware of this.

**Comment by joshdholtz** [comment]
Looking into right now!

**Comment by joshdholtz** [comment]
@maskedpear Sorry about the issues! Are you able to change your `get_version_number` to specify a target now?

Before `2.86.x`, the `get_version_number` was picking which target to get the version for an incorrect way and was leading to many confusing bugs. This new version will correctly pull from the target that is specified and will auto-choose a target if there is only one. How many targets do you have?

**Comment by maskedpear** [comment]
@joshdholtz Thank you for your response. I didn't realise there's a new Masterfile version. We currently using `2.3.0`. I will make sure is using the latest.
After doing that, how do I specify the target? We have about 5-6 targets.

**Comment by KaneCheshire** [comment]
Hey @maskedpear! We're in the process of making some large changes to remove the need for a Provfile which should simplify things. 

With the new version of the MasterFastfile you should only need to provide a couple of things like an export options plist, a path to your project. The README will be updated as well but I'm more than happy to help you get set up with the new version once it's properly released.

There's a release branch in PR (#53) currently, you can test that out by pointing your Fastfile import to that branch rather than a tag if you want? I've set a project up here at TAB successfully using that branch already so confident it should work okay :)

**Comment by KaneCheshire** [comment]
I've been able to reproduce this issue even pointing to the as-yet unreleased version 4.0 of the MasterFastfile, so I'll look at getting this fix in before we release it if we can.

**Comment by KaneCheshire** [comment]
https://docs.fastlane.tools/actions/get_version_number/ 

According to the docs everything is optional, unless you have multiple targets. So we'll have to define a target somehow using the MasterFastfile environment variables

**Comment by AncAinu** [comment]
Proposed fix: https://github.com/theappbusiness/MasterFastfile/pull/56

**Comment by KaneCheshire** [comment]
Hi @maskedpear :) this has been fixed now as part of the v4.0.0 release.

To take advantage of this fix you'll need to define a new environment variable `TAB_TARGET_FOR_BUILD_NUMBER` which is the name of the target you want to use for getting the current build number.

Thanks for reporting this!
